version: '3.9'
services:
  db:
    image: postgres:15.3
    container_name: to_do_db

    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    network_mode: bridge